fix typo in README
fluent/fluentd-kubernetes-daemonset pull request #1428
Opened 2023-04-21 22:43 UTC by spowelljr

2023-04-22 00:13 UTC, daipom approved these changes
LGTM. Thanks!

2023-04-24 00:59 UTC, ashie requested changes

2023-04-24 00:59 UTC, ashie commented on README.md
> +If you want to use above non published images, build it by yourself. Dockerfile itself is still maintained in this repository.
Could you fix template/README.md.erb instead?
README.md is a generated file from it, so that it will be overwritten on every release.

2023-04-25 03:25 UTC, ashie approved these changes

2023-04-25 03:25 UTC, merged

2023-04-25 03:25 UTC, ashie commented
Thanks!