v1.16.2
fluent/fluentd-kubernetes-daemonset pull request #1446
Opened 2023-07-19 02:48 UTC by ashie

2023-07-19 10:12 UTC, cosmo0920 requested changes
We need to get rid of elasticsearch6 image that is already EOL:
https://www.elastic.co/jp/support/eol
Note that 2023/08/01 or ES v9.0.0 released date should be EOL for Elasticsearch7.

2023-07-20 00:16 UTC, ashie commented
> We need to get rid of elasticsearch6 image that is already EOL: https://www.elastic.co/jp/support/eol Note that 2023/08/01 or ES v9.0.0 released date should be EOL for Elasticsearch7.

Thanks for notifying it.
Should it be done in this PR? 
I want to remove obsolete images ( like as #553) in another PR.
Elasicsearch6 image isn't pushed to Docker Hub since some time ago already.

2023-07-20 05:15 UTC, cosmo0920 approved these changes

2023-07-20 05:26 UTC, merged

2023-07-20 05:26 UTC, ashie commented
Thanks for your review!