fix elastic templates so that tail log parser works and daemonsets dont crash
fluent/fluentd-kubernetes-daemonset pull request #1450
Opened 2023-08-03 03:45 UTC by jamesla

This fix provides 2 updates to the elastic daemonsets.

1. Solves an issue where there was an infinite loop because fluent logs were being exported to elastic which would create fluent entries...  and daemonsets were tending to crash.

2. Solves an issue where tail parser was not working because it did not have a parser associated. I have added a parser to parse docker style log entries as that's what most people are using, however if you are using something else it would be quite clear for a user to see how to modify it.

This is documented here (as well as other various github issues which appears to trip a lot of people up). https://github.com/fluent/fluentd-kubernetes-daemonset/issues/434

2023-09-25 02:24 UTC, jamesla commented
bump

2023-09-27 05:41 UTC, ashie requested changes

2023-09-27 05:41 UTC, ashie commented on fluentd-daemonset-elasticsearch-rbac.yaml
> +            value: /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
It's not correct, it not valid for `@type` here:
https://github.com/fluent/fluentd-kubernetes-daemonset/blob/4066426d1a23da07e7f014ae0ca9693fdd1655a8/templates/conf/tail_container_parse.conf.erb#L2

It shoud be `cri` as described in https://github.com/fluent/fluentd-kubernetes-daemonset/issues/434#issuecomment-831801690

2023-09-27 05:41 UTC, ashie commented on fluentd-daemonset-elasticsearch.yaml
> +          - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
Ditto

2023-09-27 06:33 UTC, ashie commented
Should we make them default instead of replacing them in each configurations?

2024-01-25 10:02 UTC, closed without merging